export function baseHtml(opts: {
  title: string;
  generatedAt: string;
  gitRef: string | null;
  gitBranch: string | null;
  content: string;
}): string {
  return `<!DOCTYPE html>
<html lang="en" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${opts.title} — forge-visual</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
  <script>
    tailwind.config = {
      darkMode: 'class',
      theme: {
        extend: {
          colors: {
            dark: { 900: '#0a0a0f', 800: '#12121a', 700: '#1a1a2e', 600: '#252540' },
            accent: { DEFAULT: '#6366f1', light: '#818cf8' },
            gas: { low: '#10b981', mid: '#f59e0b', high: '#ef4444' },
          }
        }
      }
    }
  </script>
  <style>
    body { background: #0a0a0f; }
    .glass { background: rgba(18, 18, 26, 0.8); backdrop-filter: blur(12px); border: 1px solid rgba(99, 102, 241, 0.15); }
    .gas-heatmap-low { background: rgba(16, 185, 129, 0.15); color: #6ee7b7; }
    .gas-heatmap-mid { background: rgba(245, 158, 11, 0.15); color: #fcd34d; }
    .gas-heatmap-high { background: rgba(239, 68, 68, 0.15); color: #fca5a5; }
    .status-pass { color: #10b981; }
    .status-fail { color: #ef4444; }
    .status-skip { color: #6b7280; }
    .coverage-high { color: #10b981; }
    .coverage-medium { color: #f59e0b; }
    .coverage-low { color: #ef4444; }
    .bar-high { background: #10b981; }
    .bar-medium { background: #f59e0b; }
    .bar-low { background: #ef4444; }
    [x-cloak] { display: none !important; }
  </style>
</head>
<body class="text-gray-200 min-h-screen">
  <nav class="glass sticky top-0 z-50 px-6 py-3 flex items-center justify-between">
    <div class="flex items-center gap-3">
      <span class="text-accent font-bold text-lg">forge-visual</span>
      <span class="text-gray-500">|</span>
      <span class="text-sm text-gray-400">${opts.title}</span>
    </div>
    <div class="flex items-center gap-4 text-sm text-gray-500">
      ${opts.gitBranch ? `<span>${opts.gitBranch}</span>` : ""}
      ${opts.gitRef ? `<code class="bg-dark-700 px-2 py-0.5 rounded text-xs">${opts.gitRef}</code>` : ""}
      <span>${opts.generatedAt}</span>
    </div>
  </nav>
  <main class="max-w-7xl mx-auto px-6 py-8">
    ${opts.content}
  </main>
  <footer class="text-center text-gray-600 text-xs py-6">
    Generated by <span class="text-accent">forge-visual</span>
  </footer>
</body>
</html>`;
}
